spring.application.name=coding-contest-platform
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://gauravsh650_db_user:<db_password>@cluster0.ux96y8n.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=coding_contest

# CORS Configuration
cors.allowed.origins=http://localhost:3000

# Judge Engine Configuration
judge.docker.image=openjdk:17-slim
judge.timeout.seconds=10
judge.memory.limit=256m
judge.temp.dir=/tmp/judge

# Async Configuration
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100


4x5AEsdNBZQATVC2
gauravsh650_db_user